import { MEDIA_CONFIG } from './media/giveawayData';
import { ContestPost, Participant } from './types';

/**
 * Automatically maps the settings from `src/media/giveawayData.ts` into the app.
 */

export interface GiveawayConfig {
  winnerCount: number;
  countdownSeconds: number;
  post: ContestPost;
  designatedWinners: Participant[];
  allParticipants: Participant[];
}

// Convert MEDIA_CONFIG.winners into Participant array
const designatedWinners: Participant[] = MEDIA_CONFIG.winners.map((w, idx) => ({
  id: `winner-${idx + 1}`,
  username: w.username,
  fullName: w.fullName,
  avatarUrl: w.profileImage,
  comment: w.comment,
  hasGif: w.hasGif,
  likesCount: 15 + idx * 7,
  timeAgo: `${idx + 1}d`,
  isValid: true,
}));

// 31 Accounts extracted from the provided giveaway participant image
const extraParticipants: Participant[] = [
  {
    id: 'p1',
    username: '_vidhu_veee',
    fullName: 'Vidhu V',
    avatarUrl: '/avatars/_vidhu_veee.jpg',
    comment: 'Super video! Hoping to win 🔥🙌',
    likesCount: 18,
    timeAgo: '1d',
    isValid: true,
  },
  {
    id: 'p2',
    username: 'jayeshgopinath',
    fullName: 'Jayesh Gopinath',
    avatarUrl: '/avatars/jayeshgopinath.jpg',
    comment: 'Awesome post bro 💛✨',
    likesCount: 9,
    timeAgo: '2d',
    isValid: true,
  },
  {
    id: 'p3',
    username: '_iamshebin__',
    fullName: 'Shebin',
    avatarUrl: '/avatars/_iamshebin__.jpg',
    comment: 'Sunset vibes & great contest 🌅🔥',
    likesCount: 14,
    timeAgo: '1d',
    isValid: true,
  },
  {
    id: 'p4',
    username: 'abelabelps',
    fullName: 'Abel P S',
    avatarUrl: '/avatars/abelabelps.jpg',
    comment: 'Nature beauty 😍 All the best everyone',
    likesCount: 7,
    timeAgo: '3d',
    isValid: true,
  },
  {
    id: 'p5',
    username: '_.mr._.perfect._.25',
    fullName: 'Mr Perfect',
    avatarUrl: '/avatars/_.mr._.perfect._.25.jpg',
    comment: 'Night ride mode on 🌙🤟',
    likesCount: 12,
    timeAgo: '2d',
    isValid: true,
  },
  {
    id: 'p6',
    username: 'naseema_kp___',
    fullName: 'Naseema K P',
    avatarUrl: '/avatars/naseema_kp___.jpg',
    comment: 'Cuties ❤️ Winning this insha Allah',
    likesCount: 15,
    timeAgo: '1d',
    isValid: true,
  },
  {
    id: 'p7',
    username: 'anxiidh',
    fullName: 'Anshid',
    avatarUrl: '/avatars/anxiidh.jpg',
    comment: 'Great content 🔥🙌',
    likesCount: 6,
    timeAgo: '4d',
    isValid: true,
  },
  {
    id: 'p8',
    username: 'mr.sam_vlm',
    fullName: 'Sam VLM',
    avatarUrl: '/avatars/mr.sam_vlm.jpg',
    comment: 'Rose vibes 🌹 Best of luck!',
    likesCount: 8,
    timeAgo: '2d',
    isValid: true,
  },
  {
    id: 'p9',
    username: 'sinnannnnn11',
    fullName: 'Sinan',
    avatarUrl: '/avatars/sinnannnnn11.jpg',
    comment: 'Awesome vibe bro 🚀💜',
    likesCount: 11,
    timeAgo: '1d',
    isValid: true,
  },
  {
    id: 'p10',
    username: 'ansaf_kunjathur',
    fullName: 'Ansaf Kunjathur',
    avatarUrl: '/avatars/ansaf_kunjathur.jpg',
    comment: 'Count me in! Top quality 🔥',
    likesCount: 22,
    timeAgo: '3d',
    isValid: true,
  },
  {
    id: 'p11',
    username: 'lauren__px',
    fullName: 'Lauren P X',
    avatarUrl: '/avatars/lauren__px.jpg',
    comment: 'Looking fire 🔥 Hope I get selected!',
    likesCount: 19,
    timeAgo: '1d',
    isValid: true,
  },
  {
    id: 'p12',
    username: 'mazinmohammeddddd',
    fullName: 'Mazin Mohammed',
    avatarUrl: '/avatars/mazinmohammeddddd.jpg',
    comment: 'Style icon! Good luck to all 🧡',
    likesCount: 13,
    timeAgo: '2d',
    isValid: true,
  },
  {
    id: 'p13',
    username: 'adh_i.i_',
    fullName: 'Adhi',
    avatarUrl: '/avatars/adh_i.i_.jpg',
    comment: 'Nice post! Let’s go 🤟',
    likesCount: 8,
    timeAgo: '1d',
    isValid: true,
  },
  {
    id: 'p14',
    username: '_.mr._.komban._',
    fullName: 'Mr Komban',
    avatarUrl: '/avatars/_.mr._.komban._.jpg',
    comment: 'Komban style 🔴⚫ Best wishes!',
    likesCount: 24,
    timeAgo: '3d',
    isValid: true,
  },
  {
    id: 'p15',
    username: '__alexpandian__',
    fullName: 'Alex Pandian',
    avatarUrl: '/avatars/__alexpandian__.jpg',
    comment: 'Mass entry! Great giveaway 🔥',
    likesCount: 17,
    timeAgo: '2d',
    isValid: true,
  },
  {
    id: 'p16',
    username: 'visual._.craftsman',
    fullName: 'Visual Craftsman',
    avatarUrl: '/avatars/visual._.craftsman.jpg',
    comment: 'Top tier visuals 🎬📸 Keep it up',
    likesCount: 31,
    timeAgo: '1d',
    isValid: true,
  },
  {
    id: 'p17',
    username: 'vineeth8987',
    fullName: 'Vineeth',
    avatarUrl: '/avatars/vineeth8987.jpg',
    comment: 'Solid vibe! Hope to win this 💯',
    likesCount: 10,
    timeAgo: '2d',
    isValid: true,
  },
  {
    id: 'p18',
    username: '__thahir_t',
    fullName: 'Thahir T',
    avatarUrl: '/avatars/__thahir_t.jpg',
    comment: 'Concert energy 🔥💥 Best post',
    likesCount: 16,
    timeAgo: '1d',
    isValid: true,
  },
  {
    id: 'p19',
    username: 'thohir_shan___',
    fullName: 'Thohir Shan',
    avatarUrl: '/avatars/thohir_shan___.jpg',
    comment: 'Fingers crossed 🤞🔥',
    likesCount: 7,
    timeAgo: '4d',
    isValid: true,
  },
  {
    id: 'p20',
    username: 'a_j_u__ajmal',
    fullName: 'Aju Ajmal',
    avatarUrl: '/avatars/a_j_u__ajmal.jpg',
    comment: 'Golden hour vibes 🌅🙌',
    likesCount: 14,
    timeAgo: '2d',
    isValid: true,
  },
  {
    id: 'p21',
    username: 'ameeeee._____',
    fullName: 'Ameen',
    avatarUrl: '/avatars/ameeeee._____.jpg',
    comment: 'Camera ready 📸 Great giveaway',
    likesCount: 20,
    timeAgo: '1d',
    isValid: true,
  },
  {
    id: 'p22',
    username: 'monsoon_abaya',
    fullName: 'Monsoon Abaya',
    avatarUrl: '/avatars/monsoon_abaya.jpg',
    comment: 'Beautiful collection! Support from Monsoon Abaya 💜',
    likesCount: 25,
    timeAgo: '3d',
    isValid: true,
  },
  {
    id: 'p23',
    username: 'ansal__anzu',
    fullName: 'Ansal Anzu',
    avatarUrl: '/avatars/ansal__anzu.jpg',
    comment: 'Nice one bro 👍✨',
    likesCount: 9,
    timeAgo: '2d',
    isValid: true,
  },
  {
    id: 'p24',
    username: 'angamalykaran__6848',
    fullName: 'Angamaly Karan',
    avatarUrl: '/avatars/angamalykaran__6848.jpg',
    comment: 'Suit up! Best giveaway of the month 👔🔥',
    likesCount: 28,
    timeAgo: '1d',
    isValid: true,
  },
  {
    id: 'p25',
    username: 'jipson_vs',
    fullName: 'Jipson V S',
    avatarUrl: '/avatars/jipson_vs.jpg',
    comment: 'Cool post! Count me in 💙',
    likesCount: 12,
    timeAgo: '3d',
    isValid: true,
  },
  {
    id: 'p26',
    username: 'g_o_p_i_k_a_22_s',
    fullName: 'Gopika S',
    avatarUrl: '/avatars/g_o_p_i_k_a_22_s.jpg',
    comment: 'Green aesthetic 🌿 Wishing everyone the best',
    likesCount: 15,
    timeAgo: '2d',
    isValid: true,
  },
  {
    id: 'p27',
    username: 'itz_me___mansoor',
    fullName: 'Mansoor',
    avatarUrl: '/avatars/itz_me___mansoor.jpg',
    comment: 'Swag on point 😎🔥',
    likesCount: 19,
    timeAgo: '1d',
    isValid: true,
  },
  {
    id: 'p28',
    username: '_thahir.fjo',
    fullName: 'Thahir FJO',
    avatarUrl: '/avatars/_thahir.fjo.jpg',
    comment: 'Rose lover 🌹 All the best!',
    likesCount: 8,
    timeAgo: '4d',
    isValid: true,
  },
  {
    id: 'p29',
    username: 'irfahnh',
    fullName: 'Irfan H',
    avatarUrl: '/avatars/irfahnh.jpg',
    comment: 'Neon vibes 🕶️ Let’s win this!',
    likesCount: 21,
    timeAgo: '1d',
    isValid: true,
  },
  {
    id: 'p30',
    username: 'utha_ya_06',
    fullName: 'Uthaya',
    avatarUrl: '/avatars/utha_ya_06.jpg',
    comment: 'Biker life 🏍️🔥 Full support!',
    likesCount: 27,
    timeAgo: '2d',
    isValid: true,
  },
  {
    id: 'p31',
    username: 'ayashhamd_',
    fullName: 'Ayash Hamd',
    avatarUrl: '/avatars/ayashhamd_.jpg',
    comment: 'Cute entry 🥰 Best of luck everyone!',
    likesCount: 14,
    timeAgo: '1d',
    isValid: true,
  },
];

export const GIVEAWAY_CONFIG: GiveawayConfig = {
  winnerCount: MEDIA_CONFIG.winnerCount || 4,
  countdownSeconds: 8,
  post: {
    id: 'post_01',
    title: MEDIA_CONFIG.giveawayTitle,
    authorUsername: MEDIA_CONFIG.authorUsername,
    authorName: MEDIA_CONFIG.authorName,
    authorAvatar: MEDIA_CONFIG.authorAvatar,
    postImage: MEDIA_CONFIG.videoImage,
    caption: MEDIA_CONFIG.videoCaption,
    commentsCount: MEDIA_CONFIG.commentsCount,
    likesCount: MEDIA_CONFIG.likesCount,
    isVerified: true,
    resultCode: MEDIA_CONFIG.resultCode || 'REHEUV',
    resultLink: MEDIA_CONFIG.resultLink || 'smpl.rs/g/REHEUV',
  },
  designatedWinners,
  allParticipants: [...designatedWinners, ...extraParticipants],
};
